%toString dieta bulking
toStringBulking:-
   nl,nl,
   write('            -------------------------------- TREINO PARA BULKING --------------------------------  '),
   nl,nl,
   write('      --- Cafe da manha ---  '),  
   nl,nl,
   write('- Aveia (3 colheres de sopa);'), 
   nl,nl,
   write('- Ovo inteiro (2 unidades);'), 
   nl,nl,
   write('- Ameixas (10g)'),
   nl,nl,
   write('      --- Lanche ---   '), 
   nl,nl,
   write('- Batata doce (100g);'),
   nl,nl,
   write('- Peito de frango (90g);'),
   nl,nl,
   write('- Pao integral (2 fatias);'), 
   nl,nl,
   write('      --- Lanche (2) ---'),  
   nl,nl,
   write('- Banana (1 unidade);'),  
   nl,nl,
   write('- Pasta de amendoim;'),  
   nl,nl,
   write('- Queijo (2 fatias)'),  
   nl,nl,
   write('      --- Almoco ---'),  
   nl,nl,  
   write('- Beterrabas (2 unidades de 70g);'),  
   nl,nl,
   write('- Suco de uva (100ml);'),  
   nl,nl,
   write('- Macarrao integral (40g);'),  
   nl,nl,
   write('- Clara de ovo (4 unidades);'),  
   nl,nl,
   write('- Creatina (5g opcional)'), 
   nl,nl,
   write('      --- Lanche pos treino ---'),  
   nl,nl,
   write('- Whey (25g);'),  
   nl,nl,
   write('- Glutamina (5g)'),  
   nl,nl,
   write('      --- Jantar ---'),  
   nl,nl,
   write('- Arroz integral (4 colheres de sopa);'),  
   nl,nl,
   write('- Peixe (120g)'),  
   nl,nl,
   write('      --- Lanche pos jantar ---'),  
   nl,nl,
   write('- Batata doce (60g);'),  
   nl,nl,
   write('- Brocolis, alface;'),  
   nl,nl,
   write('- Omega 3 (600mg)'),  
   nl,nl,
   write('      ---- AS REFEICOES SAO FEITAS A CADA 3H ---- '),
   nl,nl,
   write('Pressione Enter para voltar ao menu principal').
   

%toString dieta cutting
toStringCutting:-  
   nl,nl,
   write('            --------------------------------- TREINO PARA CUTTING --------------------------------  '),
   nl,nl,
   write('      --- Cafe da manha --- ') ,
   nl,nl,
   write('- Tapica com ovos (2 unidades);'),
   nl,nl,
   write('- Mamao (1 fatia grande);'),
   nl,nl,
   write('- Omega 3 (1000mg)'),
   nl,nl,
   write('      --- Almoco --- '),
   nl,nl,
   write('- Abobora, chuchu, couve flor, brocolis, alface (100g)'),
   nl,nl,
   write('- Peito de frango (120g)'),
   nl,nl,
   write('- Azeite de oliva (1 colher de sopa)'),
   nl,nl,
   write('      --- Lanche  --- '),
   nl,nl,
   write('- Aveia (3 colheres de sopa);'),
   nl,nl,
   write('- Iogurte natural desnatado (200ml);'),
   nl,nl,
   write('- Laranja (1 unidade);'),
   nl,nl,
   write('      --- Jantar --- '),
   nl,nl,
   write('- Abobrinha, espinafre, cenoura (3 porcoes de hortalicas);'),
   nl,nl,
   write('- Arroz integral (2 colheres de sopa);'),
   nl,nl,
   write('- Ovos (3 unidades)'),
   nl,nl,
   write('Pressione Enter para voltar ao menu principal').

%toString dieta perda de peso
toStringWeightLoss:-
   nl,nl,
   write('            -------------------------------- TREINO PARA PERDA DE PESO --------------------------------'), 
   nl,nl,
   write('      --- Cafe da manha ---'),  
   nl,nl,
   write('- Leite desnatado (240ml);'),
   nl,nl,
   write('- Omelete (1 ovo);'),
   nl,nl,
   write('- Tomate (1 unidade)'),
   nl,nl,
   write('      --- Almoco ---'), 
   nl,nl,
   write('- File de peixe(150g);'),
   nl,nl,
   write('- Grao de bico (2 colheres de sopa);'),
   nl,nl,
   write('- Salada cozida;'),
   nl,nl,
   write('- Abacaxi (2 fatias)'),
   nl,nl,
   write('      --- Lanche  ---'), 
   nl,nl,
   write('- Iogurte desnatado (1 unidade);'),
   nl,nl,
   write('- Linhaca (2 colheres de sopa);'),
   nl,nl,
   write('      --- Jantar ---'), 
   nl,nl,
   write('- Peito de frango (150g);'),
   nl,nl,
   write('- Feijao (2 colheres de sopa);'),
   nl,nl,
   write('- Salada crua;'),
   nl,nl,
   write('- Laranja (1 unidade)'),
   nl,nl,
   write('Pressione Enter para voltar ao menu principal').