%toString treino iniciante
toStringTreinoIni:-
    nl,nl,
    write('-------------------------------- TREINO INICIANTE xD --------------------------------'),
    nl,nl,
    write('Segunda & Quinta: '),
    nl,nl,
    write('- Leg Press 2x15'),
    nl,nl,
    write('- Supino reto 2x15'),
    nl,nl,
    write('- Remada na Maquina 2x15'),
    nl,nl,
    write('- Leg raises 3x10'),
    nl,nl,
    write('Terca & Sexta: '),
    nl,nl,
    write('- Triceps Maquina3x10'),
    nl,nl,
    write('- Supino reto 2x15'),
    nl,nl,
    write('- Remada na Maquina 2x15'),
    nl,nl,
    write('- Agachamento 3x10'),
    nl,nl,
    write('Quarta & Sabado: '),
    nl,nl,
    write('- Mesa Flexora 3x10'),
    nl,nl,
    write('- Biceps alternados 3x20write(10 cada braco)'),
    nl,nl,
    write('- Barra reta 3x10'),
    nl,nl,
    write('Domingo - Rest day')
. 

%toString treino medio
toStringTreinoMed:-
    nl,nl,
    write('-------------------------------- TREINO MEDIO xD --------------------------------'),
    nl,nl,
    write('Segunda & Quinta: '),
    nl,nl,
    write('- Leg press 3x10'),
    nl,nl,
    write('- Extensora 3x8'),
    nl,nl,
    write('- Agachamento 3x12'),
    nl,nl,
    write('- Panturrilha write(free)'),
    nl,nl,
    write('Terca & Sexta: '),
    nl,nl,
    write('- Remada alta 3x8'),
    nl,nl,
    write('- Triceps testa 3x10'),
    nl,nl,
    write('- Elevacao lateral 3x10'),
    nl,nl,
    write('- ABS write(free)'),
    nl,nl,
    write('Quarta & Sabado: '),
    nl,nl,
    write('- Supino inclinado 3x8'),
    nl,nl,
    write('- Pullover 3x8'),
    nl,nl,
    write('- Supino com halteres 3x10'),
    nl,nl,
    write('- Peck deck 3x8'),
    nl,nl,
    write('- Panturrilha write(free)'),
    nl,nl,
    write('Domingo - Rest day').

%toString treino avancado 
toStringTreinoAva:-
    nl,nl,
    write('-------------------------------- TREINO AVANCADO xD --------------------------------'),
    nl,nl,
    write('Segunda & Quinta: '),
    nl,nl,
    write('- Peck deck 3x15'),
    nl,nl,
    write('- Supino inclinado com halteres 3x8'),
    nl,nl,
    write('- Supino reto com barra 3x12'),
    nl,nl,
    write('- Pullover 3x12'),
    nl,nl,
    write('- Panturrilha write(free)'),
    nl,nl,
    write('Terca & Sexta: '),
    nl,nl,
    write('- Flexora deitado 3x15'),
    nl,nl,
    write('- Leg press 2x15'),
    nl,nl,
    write('- Stiff 3x15'),
    nl,nl,
    write('- Extensora 3x15'),
    nl,nl,
    write('- ABS write(free)'),
    nl,nl,
    write('Quarta & Sabado: '),
    nl,nl,
    write('- Triceps pulley 3x15'),
    nl,nl,
    write('- Remada serrote 3x15'),
    nl,nl,
    write('- Polia 3x15'),
    nl,nl,
    write('- Remada supinada 3x8'),
    nl,nl,
    write('- Panturrilha write(free)'),
    nl,nl,
    write('Domingo - Rest day').
